/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SegurancaRouteImport } from './routes/seguranca'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HomeRouteImport } from './routes/home'
import { Route as GlossarioRouteImport } from './routes/glossario'
import { Route as AppsRouteImport } from './routes/apps'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppsYoutubeRouteImport } from './routes/apps.youtube'
import { Route as AppsWhatsappRouteImport } from './routes/apps.whatsapp'
import { Route as AppsInstagramRouteImport } from './routes/apps.instagram'
import { Route as AppsGoogleRouteImport } from './routes/apps.google'
import { Route as AppsContatosRouteImport } from './routes/apps.contatos'
import { Route as AppsConfiguracoesRouteImport } from './routes/apps.configuracoes'
import { Route as AppsCameraRouteImport } from './routes/apps.camera'

const SegurancaRoute = SegurancaRouteImport.update({
  id: '/seguranca',
  path: '/seguranca',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const GlossarioRoute = GlossarioRouteImport.update({
  id: '/glossario',
  path: '/glossario',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsRoute = AppsRouteImport.update({
  id: '/apps',
  path: '/apps',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsYoutubeRoute = AppsYoutubeRouteImport.update({
  id: '/youtube',
  path: '/youtube',
  getParentRoute: () => AppsRoute,
} as any)
const AppsWhatsappRoute = AppsWhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => AppsRoute,
} as any)
const AppsInstagramRoute = AppsInstagramRouteImport.update({
  id: '/instagram',
  path: '/instagram',
  getParentRoute: () => AppsRoute,
} as any)
const AppsGoogleRoute = AppsGoogleRouteImport.update({
  id: '/google',
  path: '/google',
  getParentRoute: () => AppsRoute,
} as any)
const AppsContatosRoute = AppsContatosRouteImport.update({
  id: '/contatos',
  path: '/contatos',
  getParentRoute: () => AppsRoute,
} as any)
const AppsConfiguracoesRoute = AppsConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AppsRoute,
} as any)
const AppsCameraRoute = AppsCameraRouteImport.update({
  id: '/camera',
  path: '/camera',
  getParentRoute: () => AppsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/apps': typeof AppsRouteWithChildren
  '/glossario': typeof GlossarioRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/seguranca': typeof SegurancaRoute
  '/apps/camera': typeof AppsCameraRoute
  '/apps/configuracoes': typeof AppsConfiguracoesRoute
  '/apps/contatos': typeof AppsContatosRoute
  '/apps/google': typeof AppsGoogleRoute
  '/apps/instagram': typeof AppsInstagramRoute
  '/apps/whatsapp': typeof AppsWhatsappRoute
  '/apps/youtube': typeof AppsYoutubeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/apps': typeof AppsRouteWithChildren
  '/glossario': typeof GlossarioRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/seguranca': typeof SegurancaRoute
  '/apps/camera': typeof AppsCameraRoute
  '/apps/configuracoes': typeof AppsConfiguracoesRoute
  '/apps/contatos': typeof AppsContatosRoute
  '/apps/google': typeof AppsGoogleRoute
  '/apps/instagram': typeof AppsInstagramRoute
  '/apps/whatsapp': typeof AppsWhatsappRoute
  '/apps/youtube': typeof AppsYoutubeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/apps': typeof AppsRouteWithChildren
  '/glossario': typeof GlossarioRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/seguranca': typeof SegurancaRoute
  '/apps/camera': typeof AppsCameraRoute
  '/apps/configuracoes': typeof AppsConfiguracoesRoute
  '/apps/contatos': typeof AppsContatosRoute
  '/apps/google': typeof AppsGoogleRoute
  '/apps/instagram': typeof AppsInstagramRoute
  '/apps/whatsapp': typeof AppsWhatsappRoute
  '/apps/youtube': typeof AppsYoutubeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/apps'
    | '/glossario'
    | '/home'
    | '/login'
    | '/seguranca'
    | '/apps/camera'
    | '/apps/configuracoes'
    | '/apps/contatos'
    | '/apps/google'
    | '/apps/instagram'
    | '/apps/whatsapp'
    | '/apps/youtube'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/apps'
    | '/glossario'
    | '/home'
    | '/login'
    | '/seguranca'
    | '/apps/camera'
    | '/apps/configuracoes'
    | '/apps/contatos'
    | '/apps/google'
    | '/apps/instagram'
    | '/apps/whatsapp'
    | '/apps/youtube'
  id:
    | '__root__'
    | '/'
    | '/apps'
    | '/glossario'
    | '/home'
    | '/login'
    | '/seguranca'
    | '/apps/camera'
    | '/apps/configuracoes'
    | '/apps/contatos'
    | '/apps/google'
    | '/apps/instagram'
    | '/apps/whatsapp'
    | '/apps/youtube'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppsRoute: typeof AppsRouteWithChildren
  GlossarioRoute: typeof GlossarioRoute
  HomeRoute: typeof HomeRoute
  LoginRoute: typeof LoginRoute
  SegurancaRoute: typeof SegurancaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/seguranca': {
      id: '/seguranca'
      path: '/seguranca'
      fullPath: '/seguranca'
      preLoaderRoute: typeof SegurancaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/glossario': {
      id: '/glossario'
      path: '/glossario'
      fullPath: '/glossario'
      preLoaderRoute: typeof GlossarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps': {
      id: '/apps'
      path: '/apps'
      fullPath: '/apps'
      preLoaderRoute: typeof AppsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/youtube': {
      id: '/apps/youtube'
      path: '/youtube'
      fullPath: '/apps/youtube'
      preLoaderRoute: typeof AppsYoutubeRouteImport
      parentRoute: typeof AppsRoute
    }
    '/apps/whatsapp': {
      id: '/apps/whatsapp'
      path: '/whatsapp'
      fullPath: '/apps/whatsapp'
      preLoaderRoute: typeof AppsWhatsappRouteImport
      parentRoute: typeof AppsRoute
    }
    '/apps/instagram': {
      id: '/apps/instagram'
      path: '/instagram'
      fullPath: '/apps/instagram'
      preLoaderRoute: typeof AppsInstagramRouteImport
      parentRoute: typeof AppsRoute
    }
    '/apps/google': {
      id: '/apps/google'
      path: '/google'
      fullPath: '/apps/google'
      preLoaderRoute: typeof AppsGoogleRouteImport
      parentRoute: typeof AppsRoute
    }
    '/apps/contatos': {
      id: '/apps/contatos'
      path: '/contatos'
      fullPath: '/apps/contatos'
      preLoaderRoute: typeof AppsContatosRouteImport
      parentRoute: typeof AppsRoute
    }
    '/apps/configuracoes': {
      id: '/apps/configuracoes'
      path: '/configuracoes'
      fullPath: '/apps/configuracoes'
      preLoaderRoute: typeof AppsConfiguracoesRouteImport
      parentRoute: typeof AppsRoute
    }
    '/apps/camera': {
      id: '/apps/camera'
      path: '/camera'
      fullPath: '/apps/camera'
      preLoaderRoute: typeof AppsCameraRouteImport
      parentRoute: typeof AppsRoute
    }
  }
}

interface AppsRouteChildren {
  AppsCameraRoute: typeof AppsCameraRoute
  AppsConfiguracoesRoute: typeof AppsConfiguracoesRoute
  AppsContatosRoute: typeof AppsContatosRoute
  AppsGoogleRoute: typeof AppsGoogleRoute
  AppsInstagramRoute: typeof AppsInstagramRoute
  AppsWhatsappRoute: typeof AppsWhatsappRoute
  AppsYoutubeRoute: typeof AppsYoutubeRoute
}

const AppsRouteChildren: AppsRouteChildren = {
  AppsCameraRoute: AppsCameraRoute,
  AppsConfiguracoesRoute: AppsConfiguracoesRoute,
  AppsContatosRoute: AppsContatosRoute,
  AppsGoogleRoute: AppsGoogleRoute,
  AppsInstagramRoute: AppsInstagramRoute,
  AppsWhatsappRoute: AppsWhatsappRoute,
  AppsYoutubeRoute: AppsYoutubeRoute,
}

const AppsRouteWithChildren = AppsRoute._addFileChildren(AppsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppsRoute: AppsRouteWithChildren,
  GlossarioRoute: GlossarioRoute,
  HomeRoute: HomeRoute,
  LoginRoute: LoginRoute,
  SegurancaRoute: SegurancaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
